model: ensemble
save_path: models/ensemble/
weights:
  - models/model_a/efficientnet_final.pth
  - models/model_b/convnext_image_final.pth
  - models/model_c/convnext_bird_final.pth
weights_ratio:
  - 0.2
  - 0.6
  - 0.2
data:
  val: data/val_a.csv
inference:
  input_path: /kaggle/input/audio-processed/processed/126247/126247_iNat1109254_seg0.wav