# model_a.yaml
model: efficientnet
sigmoid_applied: true
save_path: models/model_a/
data:
  train: data/train_a.csv
  val: data/val_a.csv
  audio_dir: /kaggle/input/preprocess-audio
training:
  epochs: 10
  lr: 0.0003
weights:
  - models/model_a/efficientnet_final.pth
  - models/model_b/efficientnet_final.pth
  - models/model_c/efficientnet_final.pth
inference:
  input_path: /kaggle/input/audio-processed/processed/126247/126247_iNat1109254_seg0.wav
save_best_only: true
