# model_b.yaml
model: convnext_image
sigmoid_applied: true
save_path: models/model_b/
data:
  train: data/train_b.csv
  val: data/val_b.csv
  audio_dir: /kaggle/input/preprocess-audio
training:
  epochs: 5
  lr: 0.0003
weights:
  - models/model_a/efficientnet_final.pth
  - models/model_b/efficientnet_final.pth
  - models/model_c/efficientnet_final.pth
inference:
  input_path: /kaggle/input/audio-processed/processed/126247/126247_iNat1109254_seg0.wav
save_best_only: true